name: Release

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet SDK 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup dotnet SDK 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
      - name: Push to MyGet
        env:
          NUGET_URL: https://www.myget.org/F/jbogard-ci/api/v3/index.json
          NUGET_API_KEY: ${{ secrets.MYGET_JBOGARD_CI_API_KEY }}
        run: ./Push.ps1
        shell: pwsh
      - name: Push to NuGet
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./Push.ps1
        shell: pwsh
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**/*